version: '3.8'

services:
  #databasec section
  teduidentitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: teduidentitydb
    environment:
        SA_PASSWORD: "Passw0rd!"
        ACCEPT_EULA: "Y"
    restart: always
    volumes:
        - tedu_identity_sqlserver_data:/var/opt/mssql
    ports:
        - "1436:1433"

volumes:
  tedu_identity_sqlserver_data:
    external: false